/** micromatch 
 * 
 *  there are two arrays created from this, 
 *      files: items without trailing slash  
 *      dirs: items/
 * 
 *  mm.isMatch(dirItem, ignoreArr, {nocase: true}))
 * 
 */
module.exports = [
    '*.pyc',
    '*.swo',
    '*.swp',
    '*logo.*',
    '.DS_Store',
    '.coverage_data/',
    '.coverage_debug/',
    '.coverignore',
    '.editorconfig',
    '.eslintrc',
    '.git*',
    '.hg*',
    '.idea',
    '.jsbeautifyrc',
    '.jscs.json',
    '.jscsrc',
    '.jshint*',
    '.mailmap',
    '.npmignore',
    '.spmignore',
    '.travis.yml',
    'Changes*',
    'Contributing*',
    'Gulpfile.*',
    'History*',
    'VERSIONS*',
    'benchmark/',
    'benchmarks/',
    'bower.json',
    'component.json',
    'composer.json',
    'coverage.html',
    'coverage/',
    'demo/',
    'demos/',
    'doc/',
    'docs/',
    'example/',
    'examples/',
    'gruntfile.*',
    'npm-debug.log',
    'spec/',
    'test.js',
    'test/',
    'testing/',
    'tests/',
    'tmp/',
    'v8.log',
    'license*',
    'readme*',
    'changelog*',
    '.eslintrc.*',
    'eslintrc.*',
    'karma.conf.*'
];